### ISSUE TITLE
Promise based action sheet

### ISSUE THREAD

**Issue by Fedex75** [mohit23x/actionsheet-react#97]
HI, sorry if this is a silly question but do you think there is a way to create a promise-based wrapper around the Action Sheet component so that i could do something like this:
```
myActionSheet (/*Component with props*/)
.then (action => {
    /*A button was pressed*/
})
.catch (() => {
    /*Action sheet was closed or the cancel button was pressed*/
})
```

Actually i've already created a wrapper that takes a title and some buttons and returns an iOS style action sheet but the promise part beats me. This would be awesome because then i could use the action sheet sort of like the window.confirm function.

Thanks in advance.

**Comment by mohit23x** [comment]
the `open` method internally does a react state update in the action sheet component, with the current implementation you can't add promise based logic.

**Comment by Fedex75** [comment]
Yeah i thought it was impossible. Thanks for the answer.
